/**
 * generateSessionReport.ts
 * Builds and downloads a PDF documenting every update made in this
 * development session for the Wedage & Co. Fleet Management System.
 *
 * Generated by  : Esystemlk
 * Contact       : 0765711396
 * Website       : www.esystemlk.com
 * Address       : 618 Jana Jaya City Mall, Rajagiriya, Sri Lanka
 */

// @ts-ignore
import jsPDF from 'jspdf';

// ─── Colour palette ──────────────────────────────────────────────────────────
const C = {
  indigo:      [63,  81, 181] as [number, number, number],
  indigoLight: [232,234,246] as [number, number, number],
  violet:      [103, 58, 183] as [number, number, number],
  dark:        [15,  23,  42] as [number, number, number],
  mid:         [51,  65,  85] as [number, number, number],
  muted:       [100,116,139] as [number, number, number],
  light:       [241,245,249] as [number, number, number],
  white:       [255,255,255] as [number, number, number],
  emerald:     [16, 185, 129] as [number, number, number],
  amber:       [245,158,  11] as [number, number, number],
  red:         [239, 68, 68 ] as [number, number, number],
};

// ─── Change data ─────────────────────────────────────────────────────────────
interface Change {
  file?: string;
  action: 'NEW' | 'MOD' | 'FIX' | 'UPD';
  description: string;
}
interface Section {
  number: number;
  title: string;
  subtitle: string;
  color: [number, number, number];
  changes: Change[];
}

const SECTIONS: Section[] = [
  {
    number: 1,
    title: 'Mock Data → Real Firestore Database',
    subtitle: 'Every hardcoded array and fake number replaced with live Firestore connections',
    color: C.emerald,
    changes: [
      { file: 'src/pages/documents/DocumentsPage.tsx',       action: 'MOD', description: 'Full Firebase Storage integration — real file upload, download, and delete' },
      { file: 'src/pages/staff/AttendancePage.tsx',          action: 'MOD', description: 'Attendance records saved to and loaded from Firestore (keyed by date)' },
      { file: 'src/pages/fleet/AdvancedFleetDashboard.tsx',  action: 'MOD', description: 'Fleet charts use real fuel-transaction data from Firestore' },
      { file: 'src/pages/financial/FinancialDashboard.tsx',  action: 'MOD', description: 'Cost analytics computed from real invoices, salaries, and fuel transactions' },
      { file: 'src/pages/reports/ReportsPage.tsx',           action: 'MOD', description: 'Maintenance pie-chart categories derived from live maintenance records' },
      { file: 'src/services/gatePassService.ts',             action: 'FIX', description: 'Random ID collision fixed — base-36 timestamp pattern' },
      { file: 'src/services/grnService.ts',                  action: 'FIX', description: 'Random ID collision fixed' },
      { file: 'src/services/poService.ts',                   action: 'FIX', description: 'Random ID collision fixed' },
      { file: 'src/services/jobCardService.ts',              action: 'FIX', description: 'Random ID collision fixed' },
      { file: 'src/services/logService.ts',                  action: 'FIX', description: 'Random ID collision fixed' },
      { file: 'src/services/visitorLogService.ts',           action: 'FIX', description: 'Random ID collision fixed' },
      { file: 'src/pages/logs/LogFormPage.tsx',              action: 'FIX', description: 'Random ID collision fixed' },
    ],
  },
  {
    number: 2,
    title: 'New Service Files Created',
    subtitle: 'Brand-new backend service modules wired to Firestore and Firebase Storage',
    color: C.indigo,
    changes: [
      { file: 'src/config/fuelTypes.ts',             action: 'NEW', description: 'Central fuel-type config: 9 types with labels, short labels, and Tailwind color classes' },
      { file: 'src/services/documentService.ts',     action: 'NEW', description: 'Firebase Storage + Firestore CRUD for company documents; auto-detects MIME type and human-readable file size' },
      { file: 'src/services/attendanceService.ts',   action: 'NEW', description: 'Firestore attendance service — one document per calendar date with upsert pattern (setDoc)' },
      { file: 'src/services/configService.ts',       action: 'NEW', description: 'Dynamic custom inventory categories and custom fuel types stored in Firestore (persistent, shared across users)' },
    ],
  },
  {
    number: 3,
    title: 'Fuel Types Expansion',
    subtitle: 'Expanded from 2 types to 9 — all colour-coded pill buttons',
    color: C.amber,
    changes: [
      { file: 'src/config/fuelTypes.ts',                        action: 'NEW', description: 'FUEL_TYPE_VALUES: diesel, super-diesel, petrol, petrol-95, cng, lpg, electric, kerosene, other' },
      { file: 'src/services/fleetService.ts',                   action: 'MOD', description: 'Vehicle.fuelType widened from "diesel"|"petrol" to full FuelType union' },
      { file: 'src/services/fuelStockService.ts',               action: 'MOD', description: 'FuelTransaction.fuelType widened to full FuelType union' },
      { file: 'src/services/inventoryService.ts',               action: 'MOD', description: 'Fuel sub-category list updated to match 9 fuel labels; InventoryItemExtended.fuelType widened' },
      { file: 'src/pages/fleet/VehicleFormPage.tsx',            action: 'UPD', description: '2-button toggle replaced with 3-column colour-coded pill grid for all 9 fuel types' },
      { file: 'src/pages/inventory/FuelIssueFormPage.tsx',      action: 'UPD', description: 'Same 3-column pill grid; auto-selects matching type when a stock item is chosen' },
      { file: 'src/pages/inventory/InventoryItemFormPage.tsx',  action: 'UPD', description: 'Fuel type <select> now lists all 9 types with full human-readable labels' },
      { file: 'src/components/shared/QuickAddModal.tsx',        action: 'UPD', description: 'Fuel type dropdown updated to 9 options' },
    ],
  },
  {
    number: 4,
    title: 'Dynamic Custom Categories & Fuel Types',
    subtitle: 'Users can add their own categories and fuel types directly from forms — saved to Firestore',
    color: C.violet,
    changes: [
      { file: 'src/services/configService.ts',                  action: 'NEW', description: 'Firestore collections: custom_inventory_categories & custom_fuel_types with full CRUD' },
      { file: 'src/services/inventoryService.ts',               action: 'MOD', description: 'InventoryCategory type uses (string & {}) trick for autocomplete + open-ended custom strings; generateSKU handles unknown slugs' },
      { file: 'src/pages/inventory/InventoryItemFormPage.tsx',  action: 'UPD', description: 'Inline "+ New Type" dashed tile — type name + optional sub-categories → saves to Firestore, immediately selectable; custom tiles shown in violet' },
      { file: 'src/pages/inventory/InventoryItemFormPage.tsx',  action: 'UPD', description: 'Inline "+ Add Type" link in Fuel Configuration section — creates custom fuel type on the spot' },
      { file: 'src/pages/fleet/VehicleFormPage.tsx',            action: 'UPD', description: 'Inline "+ New" dashed pill at end of fuel grid; saves custom fuel type to Firestore and auto-selects it' },
      { file: 'src/pages/inventory/FuelIssueFormPage.tsx',      action: 'UPD', description: 'Same inline "+ New" fuel pill as VehicleFormPage' },
      { file: 'src/components/shared/QuickAddModal.tsx',        action: 'UPD', description: 'Fuel type dropdown loads custom types from Firestore alongside built-in 9' },
    ],
  },
  {
    number: 5,
    title: 'Login Page Full Redesign',
    subtitle: 'Modern dark branding panel, 3-mode auth, password reveal, and Firebase password reset',
    color: C.red,
    changes: [
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: 'Dark (gray-950) left panel with animated indigo/violet glow blobs and subtle grid overlay' },
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: '3-mode authentication state machine: Login → Signup → Reset Password' },
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: 'Show/Hide password toggle — Eye / EyeOff icon button inside the password input field' },
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: '"Forgot password?" link triggers Reset mode; calls Firebase sendPasswordResetEmail()' },
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: 'Email confirmation success card shown after reset link is dispatched' },
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: 'Icon-prefixed inputs (Mail, Lock icons); animated slide transitions between modes' },
      { file: 'src/pages/LoginPage.tsx', action: 'MOD', description: '12 Firebase error codes translated to human-readable messages' },
    ],
  },
];

// ─── PDF builder ─────────────────────────────────────────────────────────────
export function generateSessionReport(): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  const PW = 210;
  const PH = 297;
  const ML = 18;   // margin left
  const MR = 18;   // margin right
  const CW = PW - ML - MR;

  // ── helpers ─────────────────────────────────────────────────────────────
  function fill(r: number, g: number, b: number) { doc.setFillColor(r, g, b); }
  function ink(r: number, g: number, b: number)  { doc.setTextColor(r, g, b); }
  function rect(x: number, y: number, w: number, h: number, style: 'F' | 'S' | 'FD' = 'F') {
    doc.rect(x, y, w, h, style);
  }
  function bold(size: number)   { doc.setFont('helvetica', 'bold');   doc.setFontSize(size); }
  function normal(size: number) { doc.setFont('helvetica', 'normal'); doc.setFontSize(size); }
  function italic(size: number) { doc.setFont('helvetica', 'italic'); doc.setFontSize(size); }

  function addFooter(pageNum: number, totalPages: number) {
    const fy = PH - 14;
    fill(...C.dark);
    rect(0, fy - 4, PW, 18);
    bold(7);
    ink(...C.muted);
    doc.text('Generated by Esystemlk  |  0765711396  |  www.esystemlk.com  |  618 Jana Jaya City Mall, Rajagiriya, Sri Lanka',
      PW / 2, fy + 2, { align: 'center' });
    ink(...C.muted);
    normal(7);
    doc.text(`Page ${pageNum} / ${totalPages}`, PW - MR, fy + 2, { align: 'right' });
  }

  // ── COVER PAGE ───────────────────────────────────────────────────────────
  // Full dark background
  fill(...C.dark);
  rect(0, 0, PW, PH);

  // Accent stripe top
  fill(...C.indigo);
  rect(0, 0, PW, 3);

  // Left indigo bar
  fill(...C.indigo);
  rect(0, 3, 5, PH - 3);

  // Big heading
  bold(32);
  ink(...C.white);
  doc.text('Development', ML + 8, 52);
  doc.text('Session Report', ML + 8, 66);

  // Indigo underline
  fill(...C.indigo);
  rect(ML + 8, 70, 80, 1.5);

  // Sub-heading
  normal(11);
  ink(163, 163, 163);
  doc.text('Wedage & Co. Fleet Management System', ML + 8, 80);

  italic(9);
  ink(100, 116, 139);
  doc.text('All enhancements, new features, and bug fixes delivered this session', ML + 8, 88);

  // Meta card
  fill(30, 41, 59);
  const cardX = ML + 8, cardY = 100, cardW = CW - 8, cardH = 44;
  doc.roundedRect(cardX, cardY, cardW, cardH, 3, 3, 'F');

  bold(7);
  ink(...C.muted);
  doc.text('PROJECT',      cardX + 8, cardY + 10);
  doc.text('DATE',         cardX + 8, cardY + 22);
  doc.text('CLIENT',       cardX + 8, cardY + 34);
  doc.text('PREPARED BY',  cardX + 80, cardY + 10);
  doc.text('CONTACT',      cardX + 80, cardY + 22);
  doc.text('WEBSITE',      cardX + 80, cardY + 34);

  normal(9);
  ink(...C.white);
  doc.text('Wedage & Co. Fleet Management System',  cardX + 30, cardY + 10);
  doc.text(new Date().toLocaleDateString('en-GB', { year:'numeric', month:'long', day:'numeric' }),
    cardX + 30, cardY + 22);
  doc.text('Wedage & Company Pvt Ltd',              cardX + 30, cardY + 34);
  doc.text('Esystemlk',           cardX + 110, cardY + 10);
  doc.text('0765 711 396',        cardX + 110, cardY + 22);
  doc.text('www.esystemlk.com',   cardX + 110, cardY + 34);

  // Summary stats row
  const statY = 160;
  const stats = [
    { val: '5',  label: 'Feature Areas' },
    { val: '4',  label: 'New Files' },
    { val: '22+',label: 'Modified Files' },
    { val: '0',  label: 'Build Errors' },
  ];
  stats.forEach((s, i) => {
    const sx = ML + 8 + i * (CW / 4);
    fill(30, 41, 59);
    doc.roundedRect(sx, statY, (CW / 4) - 4, 28, 3, 3, 'F');
    bold(20);
    ink(...C.indigo);
    doc.text(s.val, sx + (CW/4-4)/2, statY + 14, { align: 'center' });
    bold(7);
    ink(...C.muted);
    doc.text(s.label.toUpperCase(), sx + (CW/4-4)/2, statY + 22, { align: 'center' });
  });

  // Summary bullets
  const bulletY = 205;
  bold(8);
  ink(...C.indigo);
  doc.text('SESSION HIGHLIGHTS', ML + 8, bulletY);
  fill(...C.indigo);
  rect(ML + 8, bulletY + 2, 40, 0.8);

  const bullets = [
    '→  Entire app migrated from mock data to live Firestore database connections',
    '→  Fuel types expanded from 2 to 9 with colour-coded pill selectors',
    '→  Users can now create custom stock categories and fuel types — stored in Firestore',
    '→  Login page fully redesigned: dark theme, password reveal, forgot-password flow',
    '→  Firebase password reset integrated with email confirmation state',
    '→  ID collision bug fixed across 7 service files using timestamp-based IDs',
  ];
  normal(8);
  ink(180, 190, 210);
  bullets.forEach((b, i) => {
    doc.text(b, ML + 8, bulletY + 12 + i * 8);
  });

  // Footer cover
  const coverFY = PH - 22;
  fill(21, 32, 55);
  rect(0, coverFY, PW, 22);

  bold(8);
  ink(...C.indigo);
  doc.text('ESYSTEMLK', ML + 8, coverFY + 8);
  normal(7);
  ink(...C.muted);
  doc.text('618 Jana Jaya City Mall, Rajagiriya, Sri Lanka', ML + 8, coverFY + 15);
  bold(7);
  ink(...C.indigo);
  doc.text('0765 711 396   •   www.esystemlk.com', PW - MR, coverFY + 15, { align: 'right' });

  // ── SECTION PAGES ────────────────────────────────────────────────────────
  const ACTION_CONFIG: Record<string, { bg: [number,number,number]; fg: [number,number,number]; label: string }> = {
    NEW: { bg: [22, 101, 52],  fg: C.white, label: 'NEW' },
    MOD: { bg: [30, 58, 138],  fg: C.white, label: 'MOD' },
    UPD: { bg: [67, 20, 107],  fg: C.white, label: 'UPD' },
    FIX: { bg: [120, 53, 15],  fg: C.white, label: 'FIX' },
  };

  const ROWS_PER_PAGE = 14;

  SECTIONS.forEach(section => {
    doc.addPage();
    let y = 0;

    // Section header band
    fill(...section.color);
    rect(0, 0, PW, 36);
    fill(...C.dark);
    rect(0, 36, PW, PH - 36);

    // Left accent
    fill(...section.color);
    rect(0, 36, 4, PH - 36);

    bold(8);
    ink(...C.white);
    doc.text(`SECTION ${section.number}`, ML, 13);
    bold(16);
    doc.text(section.title, ML, 24);
    normal(8);
    ink(220, 220, 255);
    doc.text(section.subtitle, ML, 32);

    y = 50;

    // Table header
    fill(25, 35, 60);
    rect(ML, y, CW, 8, 'F');
    bold(7);
    ink(...C.muted);
    doc.text('ACTION', ML + 3, y + 5.5);
    doc.text('FILE / COMPONENT', ML + 22, y + 5.5);
    doc.text('DESCRIPTION', ML + 98, y + 5.5);
    y += 8;

    let rowOnPage = 0;
    section.changes.forEach((ch, idx) => {
      if (rowOnPage >= ROWS_PER_PAGE) {
        // Add footer before new page
        addFooter(doc.getNumberOfPages(), SECTIONS.length + 1);
        doc.addPage();
        y = 20;
        rowOnPage = 0;
        // Re-draw column headers
        fill(25, 35, 60);
        rect(ML, y, CW, 8, 'F');
        bold(7);
        ink(...C.muted);
        doc.text('ACTION', ML + 3, y + 5.5);
        doc.text('FILE / COMPONENT', ML + 22, y + 5.5);
        doc.text('DESCRIPTION', ML + 98, y + 5.5);
        y += 8;
      }

      const rowH = 11;
      const even = idx % 2 === 0;
      fill(...(even ? [22, 30, 50] as [number,number,number] : [18, 25, 43] as [number,number,number]));
      rect(ML, y, CW, rowH, 'F');

      // Action badge
      const ac = ACTION_CONFIG[ch.action];
      fill(...ac.bg);
      doc.roundedRect(ML + 3, y + 2.5, 14, 6, 1, 1, 'F');
      bold(6);
      ink(...ac.fg);
      doc.text(ac.label, ML + 10, y + 6.8, { align: 'center' });

      // File path
      normal(7);
      ink(160, 180, 220);
      const fileStr = ch.file ?? '';
      const shortFile = fileStr.replace('src/', '').replace('pages/', '').replace('services/', '');
      doc.text(shortFile, ML + 22, y + 6.8, { maxWidth: 72 });

      // Description — truncate to fit
      ink(190, 200, 220);
      normal(7);
      const descLines = doc.splitTextToSize(ch.description, CW - 100);
      doc.text(descLines[0] + (descLines.length > 1 ? '…' : ''), ML + 98, y + 6.8);

      y += rowH;
      rowOnPage++;
    });

    addFooter(doc.getNumberOfPages(), SECTIONS.length + 1);
  });

  // ── FINAL PAGE: contact / sign-off ────────────────────────────────────────
  doc.addPage();
  fill(...C.dark);
  rect(0, 0, PW, PH);
  fill(...C.indigo);
  rect(0, 0, PW, 3);

  const signY = 70;
  bold(24);
  ink(...C.white);
  doc.text('Thank You', PW / 2, signY, { align: 'center' });
  normal(10);
  ink(...C.muted);
  doc.text('All features delivered and verified with a clean production build.', PW / 2, signY + 12, { align: 'center' });

  // Contact card
  fill(25, 37, 63);
  doc.roundedRect(ML + 15, signY + 28, CW - 30, 68, 4, 4, 'F');
  fill(...C.indigo);
  rect(ML + 15, signY + 28, 4, 68, 'F');

  bold(11);
  ink(...C.indigo);
  doc.text('ESYSTEMLK', ML + 28, signY + 43);

  bold(7);
  ink(...C.muted);
  const rows: [string, string][] = [
    ['Phone',   '0765 711 396'],
    ['Website', 'www.esystemlk.com'],
    ['Address', '618 Jana Jaya City Mall, Rajagiriya, Sri Lanka'],
  ];
  rows.forEach(([k, v], i) => {
    const ry = signY + 55 + i * 11;
    doc.text(k.toUpperCase(), ML + 28, ry);
    normal(9);
    ink(...C.white);
    doc.text(v, ML + 28 + 22, ry);
    bold(7);
    ink(...C.muted);
  });

  // Build verification badge
  fill(16, 50, 28);
  doc.roundedRect(ML + 15, signY + 108, CW - 30, 22, 3, 3, 'F');
  bold(8);
  ink(...C.emerald);
  doc.text('✓  BUILD VERIFIED  —  npm run build  →  0 errors  •  21 seconds',
    PW / 2, signY + 122, { align: 'center' });

  addFooter(doc.getNumberOfPages(), SECTIONS.length + 1);

  // ── save ────────────────────────────────────────────────────────────────────
  const date = new Date().toISOString().split('T')[0];
  doc.save(`WedageCo-Session-Report-${date}.pdf`);
}
